FROM kazuph/logspout:arm32v6
RUN apk add -U --virtual build-dependencies curl ca-certificates \
  && curl https://logdog.loggly.com/media/logs-01.loggly.com_sha12.crt -o /usr/local/share/ca-certificates/loggly.crt \
  && update-ca-certificates \
  && apk del build-dependencies \
  && rm -rf /var/cache/apk/*
